[package]
name = "draw1"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["cargo"] }
image = "0.24.7"
imageproc = "0.23.0"
itertools = "0.12.0"
rand = "0.8.5"
speedy2d = "2.0.0"
